server:
  port: 9098
# 应用名称
spring:
  application:
    name: sys-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.66.101:8848
#
#eureka:
#  instance:
#    # 使用 ip 代替实例名
#    prefer-ip-address: true
#    # 实例的主机名
#    hostname: 127.0.0.1
#    # 实例的 ID 规则
#    instance-id: sys-SERVICE
#  client:
#    serviceUrl:
#      # 注册中心地址
#      defaultZone: http://eurekalo.com:8761/eureka/